### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by chalioui** [JohnCoene/countup#3]
Hello John, 
Can you add the odometer library  Many themes are available   : https://github.hubspot.com/odometer/docs/welcome/ 
 thank you

**Comment by JohnCoene** [comment]
Done. Could you give it a try and let me know if that's what you were imagining?

```r
countup::odometer(123456, theme = "car")
```

**Comment by chalioui** [comment]
Great!! it works  thank you  :)
