### ISSUE TITLE
Add percentage in Odometer

### ISSUE THREAD

**Issue by Dave-stat** [JohnCoene/countup#4]
Is there any way to add percentage in Odometer by changing format ?

**Comment by JohnCoene** [comment]
You cannot add it as part of the odometer itself I'm afraid. You can either use CSS or HTML to do so.

```r
library(countup)
library(htmltools)

# html
browsable(
  span(odometer(123), "%")
)

# CSS
odometer(123)  %>% 
  htmlwidgets::prependContent( # place before widget
    tags$style('.odometer-inside:after {content: "%";}') # place % after
  )
```

I'm afraid the [original library](https://github.com/HubSpot/odometer) has been archived so we won't see any fixes or new features :(

**Comment by Dave-stat** [comment]
Thank you so much. span( ) creates additional space. Is there any way to get rid of extra space?

**Comment by JohnCoene** [comment]
I don't think it's possible as it's not a space but the padding around the odometer, the `.noWS` argument makes no difference. 

```r
library(countup)
library(htmltools)

# html
browsable(
  span(odometer(123, theme = "car"), "%", .noWS = "before") # use .noWs
)

# CSS
odometer(123, theme = "car")  %>% 
  htmlwidgets::prependContent( # place before widget
    tags$style('.odometer-inside:after {content: "%";}') # place % after
  )
```
